#ifndef BEH_TAVAN_FUNCTIONS_SORTING_SELECTION_HPP
#define BEH_TAVAN_FUNCTIONS_SORTING_SELECTION_HPP

#include "base.hpp"

namespace BehTavan::Functions::Sorting
{

}

#endif // BEH_TAVAN_FUNCTIONS_SORTING_SELECTION_HPP
